breakfast:
  - apple
  - 三明治
  - 包子
  - 南瓜饼
  - 叉烧包
  - 土司
  - 土豆饼
  - 咖啡
  - 小春饼
  - 年糕
  - 手抓饼
  - 曹粉
  - 松饼
  - 河粉
  - 油条
  - 烙烫面
  - 燕麦
  - 牛奶
  - 玉米
  - 皮糕
  - 米粉
  - 糊糊
  - 糯米鸡
  - 肠粉
  - 荷包蛋
  - 蛋酥卷
  - 小笼包
  - 豆浆
  - 面包
  - 饺子
  - 馄饨
  - 马蹄糕
  - 鸡蛋
  - 葱油饼

lunch:
  - 蒸排骨
  - 北京烤鸭
  - 牛排
  - 猪排
  - 牛肉饭
  - 味增汤
  - 佛跳墙
  - 黄油蟹蟹
  - 蛋包饭
  - 麦当劳
  - 凉皮
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 小笼包
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 蒸包
  - 烤肉饭
  - 烩面
  - 热干面
  - 煎饼果子
  - 生煎
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 肉夹馍
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭
  - 鲱鱼罐头

dinner:
  - 蒸排骨
  - 北京烤鸭
  - 牛排
  - 猪排
  - 牛肉饭
  - 味增汤
  - 佛跳墙
  - 黄油蟹蟹
  - 蛋包饭
  - 麦当劳
  - 凉皮
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 小笼包
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 蒸包
  - 烤肉饭
  - 烩面
  - 热干面
  - 煎饼果子
  - 生煎
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 肉夹馍
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭
  - 鲱鱼罐头
