# Bot 账户
account:
  # QQ 号码
  qq: 123456789
  # QQ 密码
  password: 123456789
  # 1:安卓手机 2:aPad 3:安卓手表 4:MacOS 5:iPad
  platform: 5

# 管理者 QQ
master: 987654321

# 复读群消息的概率%（1-100），0 不复读
repeatProb: 1

# 上线是否发送群通知，1 发送通知，0 不发送通知
groupHello: 1

# 新成员加群是否问好，1 问好，2 不问好
groupGreetingNew: 1

# 是否向新的好友问好，1 问好，2 不问好
friendGreetingNew: 1
