name: Code check

on: push

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node modules
        run: npm install
      - name: Check code
        id: check-code
        run: |
          check_output=$(npm run --silent check || :)
          check_failed=$([[ -z "$check_output" ]] && echo 'false' || echo 'true')
          check_output=$(echo -e "\`\`\`${check_output}\n\`\`\`")
          check_output="${check_output//'%'/'%25'}"
          check_output="${check_output//$'\n'/'%0A'}"
          check_output="${check_output//$'\r'/'%0D'}"
          echo ::set-output name=check_output::"$check_output"
          echo ::set-output name=check_failed::"$check_failed"
      - name: Comment if check failed
        uses: peter-evans/commit-comment@v1
        if: ${{ 'true' == steps.check-code.outputs.check_failed }}
        with:
          body: ${{ steps.check-code.outputs.check_output }}
      - name: Error if check failed
        if: ${{ 'true' == steps.check-code.outputs.check_failed }}
        run: exit -1
